#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile pipenv install --three "$@"
  local pth_certbot="$(pipenv run which certbot)"
  mkdir -p "$shome/bin"
  ln -nfs "$pth_certbot" "$shome/bin/"
}

main "$@"
