#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_certbot="$(certbot --version 2>/dev/null | awk '{print $2}' || true)"
  jq -n --arg certbot "$ver_certbot" '{certbot: $certbot}'
}

version "$@"
