#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_certbot="0.0.1"
  jq -n --arg certbot "$ver_certbot" '{certbot: $certbot}'
}

version "$@"
